#!/usr/bin/env node

const fs = require('fs');
const path = require('path');

const repoRoot = path.resolve(__dirname, '..');
const sourceRoot = path.join(repoRoot, 'webui-src');
const outputRoot = path.join(repoRoot, 'public');
const outputAssetsRoot = path.join(outputRoot, 'assets');

function ensureDir(dirPath) {
    fs.mkdirSync(dirPath, { recursive: true });
}

function readFile(filePath) {
    return fs.readFileSync(filePath, 'utf8');
}

function writeFile(filePath, content) {
    ensureDir(path.dirname(filePath));
    fs.writeFileSync(filePath, content);
}

function resolveIncludes(filePath, stack = []) {
    const absolutePath = path.resolve(filePath);
    if (stack.includes(absolutePath)) {
        throw new Error(`WebUI include cycle detected: ${[...stack, absolutePath].join(' -> ')}`);
    }

    const template = readFile(absolutePath);
    return template.replace(/\{\{\>\s*([^\s}]+)\s*\}\}/g, (_match, relativeIncludePath) => {
        const includePath = path.resolve(path.dirname(absolutePath), relativeIncludePath);
        return resolveIncludes(includePath, [...stack, absolutePath]);
    });
}

function buildHtml() {
    const templatePath = path.join(sourceRoot, 'index.template.html');
    const html = resolveIncludes(templatePath).trimEnd() + '\n';
    return `<!-- Generated by scripts/build-webui.js. Edit files under webui-src/ instead. -->\n${html}`;
}

function copyAsset(relativePath) {
    const sourcePath = path.join(sourceRoot, relativePath);
    const targetPath = path.join(outputRoot, relativePath.replace(/^(styles|scripts)\//, 'assets/'));
    writeFile(targetPath, fs.readFileSync(sourcePath));
}

function main() {
    ensureDir(outputRoot);
    ensureDir(outputAssetsRoot);

    writeFile(path.join(outputRoot, 'index.html'), buildHtml());
    copyAsset(path.join('styles', 'app.css'));
    copyAsset(path.join('scripts', 'app.js'));
}

main();
